contact: http://www.ucl.ac.uk/research-it-services/partner-with-us

title: "Research Computing Training Materials"
short: RCPS Training

defaults:
  - scope: {path: ""}
    values: {layout: default}

crumbs:
  - link: http://www.ucl.ac.uk/ISD
    text: ISD
  - link: http://www.ucl.ac.uk/isd/services
    text: Our services
  - link: http://www.ucl.ac.uk/isd/services/research-it
    text: Research IT
  - link: http://www.ucl.ac.uk/isd/services/research-it/training
    text: Training

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough","tables"]

baseurl: /training/hptclegion
