# Build all the bits for the course.
# Owain Kenway 1/April/2014

import rsdpandoc.builders
import rsdpandoc.globbers
import os

# Fix the environment because scons is broken.
env=Environment(tools=['default',rsdpandoc.builders.add_builders], 
                ENV = {'PATH' : os.environ['PATH']})

# Set what tools we have for building stuff
#env["HavePIL"]=True
#env["HaveWSD"]=True
env["HaveWebKit"]=False

rsdpandoc.builders.SlideStyle="night"
rsdpandoc.builders.SlideSyntaxHighlightingStyle="zenburn"

rsdpandoc.globbers.reveal_layout('src/intro_to_shell.md',env,"slides/","src/assets")
rsdpandoc.globbers.web_layout('src/intro_to_shell.md',env,"web/","src/assets")
